import json
import asyncio
from .input_parser import InputParser
from .data_layer import HybridDataManager
from .ai_engine import AIEngine
from .fallback_engine import FallbackEngine

USER_PROMPT_TEMPLATE = """
Destination: {destination}
Duration: {days} days
Total Budget Cap: ₹{budget}
Interests: {interests}

REAL-TIME CONTEXT:
- Weather: {weather}
- Live Trending Spots: {live_places}
- Static Attractions: {attractions}
- Static Hotels: {hotels}

TASK: Create a detailed, day-by-day itinerary using the real places listed above.

OUTPUT EXACTLY THIS JSON FORMAT (no markdown, no extra keys):
{{
  "destination": "{destination}",
  "days": [
    {{
      "day": 1,
      "theme": "Arrival and City Introduction",
      "morning":   {{ "activity": "...", "place": "...", "duration": "2h", "cost": 500 }},
      "afternoon": {{ "activity": "...", "place": "...", "duration": "3h", "cost": 1200 }},
      "evening":   {{ "activity": "...", "place": "...", "duration": "2h", "cost": 1500 }}
    }}
  ],
  "hotels": [
    {{ "name": "...", "area": "...", "price_range": "...", "price": "3500", "rating": 4.2, "location": "...", "link": "#" }}
  ],
  "flights": [
    {{
      "airline": "IndiGo",
      "price": "7500",
      "duration": "1h 45m",
      "stops": "Nonstop",
      "departure": "06:30 AM",
      "arrival": "08:15 AM",
      "travel_class": "Economy",
      "return_date": "",
      "airline_logo": "https://www.gstatic.com/flights/airline_logos/70px/6E.png"
    }}
  ],
  "budget_summary": "Estimated cost within ₹{budget}",
  "totalEstimatedCost": 0,
  "notes": "Generated by TravelNest AI."
}}

RULES:
- Generate exactly {days} day objects.
- Use ONLY places from the Static Attractions and Live Trending Spots lists above.
- Day 1 must include airport/station arrival activity.
- Last day must include a departure activity.
- Set totalEstimatedCost to the realistic sum of all activity costs.
- Flights should be realistic routes FROM Delhi (DEL) TO {destination}.
- All costs in INR (₹). No hallucinated places.
"""


class TravelAgent:
    def __init__(self):
        self.data_manager = HybridDataManager()
        self.ai_engine = AIEngine()

    async def plan_trip(self, destination: str, days: any, budget: any, interests: list = None):
        # 1. Input Parsing & Validation
        dest, days_count, budget_val, clean_interests = InputParser.parse(
            destination, days, budget, interests
        )

        # 2. Parallel async data fetch (weather + live places)
        augmented_data = await self.data_manager.get_augmented_context(dest, clean_interests)

        # 3. Build prompt
        prompt = USER_PROMPT_TEMPLATE.format(
            destination=dest,
            days=days_count,
            budget=budget_val,
            interests=", ".join(clean_interests),
            weather=json.dumps(augmented_data["live_context"]["weather"]),
            live_places=json.dumps(augmented_data["live_context"]["trending_places"]),
            attractions=json.dumps(augmented_data["static_attractions"]),
            hotels=json.dumps(augmented_data["static_hotels"]),
        )

        # 4. LLM generation — run sync Groq call in a thread so we don't block the event loop
        try:
            itinerary_data = await asyncio.to_thread(self.ai_engine.generate_trip, prompt)

            # ── Normalise response shape so frontend always gets the same keys ──
            # Some LLM outputs use "itinerary" instead of "days"
            if "days" not in itinerary_data and "itinerary" in itinerary_data:
                itinerary_data["days"] = itinerary_data.pop("itinerary")

            # Ensure flights key exists (frontend renders it)
            if "flights" not in itinerary_data or not itinerary_data["flights"]:
                itinerary_data["flights"] = _default_flights(dest)

            # Ensure hotels have the flat keys the frontend expects
            itinerary_data["hotels"] = _normalise_hotels(
                itinerary_data.get("hotels", augmented_data["static_hotels"])
            )

            # Ensure totalEstimatedCost is always a number
            if not itinerary_data.get("totalEstimatedCost"):
                itinerary_data["totalEstimatedCost"] = _calc_cost(
                    itinerary_data.get("days", []), budget_val
                )

            return {
                "success": True,
                "data": itinerary_data,
            }

        except Exception as e:
            print(f"Orchestrator: LLM failed ({e}), using FallbackEngine")
            fallback = FallbackEngine.generate(dest, days_count, budget_val, augmented_data)
            # Inject flights into fallback too
            fallback["data"]["flights"] = _default_flights(dest)
            fallback["data"]["totalEstimatedCost"] = budget_val * 0.75
            return fallback


# ── Helpers ───────────────────────────────────────────────────────────────────

def _default_flights(destination: str) -> list:
    """Return a sensible default flight pair when LLM doesn't generate one."""
    return [
        {
            "airline": "IndiGo",
            "price": "6500",
            "duration": "2h 00m",
            "stops": "Nonstop",
            "departure": "06:15 AM",
            "arrival": "08:15 AM",
            "travel_class": "Economy",
            "return_date": "",
            "airline_logo": "https://www.gstatic.com/flights/airline_logos/70px/6E.png",
        },
        {
            "airline": "Air India",
            "price": "9800",
            "duration": "2h 15m",
            "stops": "Nonstop",
            "departure": "14:00 PM",
            "arrival": "16:15 PM",
            "travel_class": "Economy",
            "return_date": "",
            "airline_logo": "https://www.gstatic.com/flights/airline_logos/70px/AI.png",
        },
    ]


def _normalise_hotels(hotels: list) -> list:
    """
    The static dataset uses area/price_range; the frontend expects name/price/rating/location/link.
    Add missing keys without losing existing ones.
    """
    normalised = []
    for h in hotels:
        raw_price_range = h.get("price_range", "")
        # Strip non-ASCII to avoid garbled ₹ from charset encoding issues
        clean_price_range = raw_price_range.encode("ascii", "ignore").decode("ascii").strip()
        price_num = _parse_price_range(clean_price_range) if clean_price_range else h.get("price", "3000")
        normalised.append({
            "name":        h.get("name", "Hotel"),
            "price":       h.get("price", price_num),
            "rating":      h.get("rating", 4.0),
            "location":    h.get("location") or h.get("area", "City Centre"),
            "link":        h.get("link", "#"),
            # Keep original keys for backwards compat
            "area":        h.get("area", ""),
            "price_range": clean_price_range,
        })
    return normalised


def _parse_price_range(price_range: str) -> str:
    """Extract the lower bound of '₹3500-₹8000' as a plain number string."""
    try:
        clean = price_range.replace("₹", "").replace(",", "").strip()
        return clean.split("-")[0].strip()
    except Exception:
        return "3000"


def _calc_cost(days: list, budget: float) -> float:
    """Sum all slot costs across all days."""
    total = 0.0
    for day in days:
        for slot in ("morning", "afternoon", "evening"):
            try:
                total += float(day.get(slot, {}).get("cost", 0) or 0)
            except (TypeError, ValueError):
                pass
    return total if total > 0 else budget * 0.75
